### Get all blogs
GET http://localhost:3003/api/blogs
Accept: application/json


### Add a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json


{
"title": "Test Blog",
"author": "Tester",
"url": "http://example.com",
"likes": 5
}